version: '3.8'
services:
  web_app:
    build: .
    ports:
      - "8080:5000" # Map host port 8080 to container port 5000
    volumes:
      - ./app:/app # Mounts the app directory for live updates during development
    environment:
      - FLASK_ENV=development # Optional: for development mode